import test from "node:test";
import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createArticleIdentity } from "./identity.js";

/**
 * Golden vectors for the article-identity contract.
 *
 * These expected values are the single source of truth for URL normalization
 * and articleId generation. Any change to a value here is an intentional
 * "articleId migration" (existing Firebase / articles.json records would need
 * re-keying) and must be reviewed as such — never edited to silence a failing
 * test. See plan: Phase 1 / Golden Tests.
 */
const GOLDEN: Array<{
  input: string;
  articleId: string;
  canonicalUrl: string;
  sourceKind: "web" | "youtube";
}> = [
  // tracking query removed, fragment dropped, query sorted, host lowercased
  { input: "https://Example.com/article?utm_source=x&id=2#top", articleId: "url_fa0d98563f8d", canonicalUrl: "https://example.com/article?id=2", sourceKind: "web" },
  // trailing slash trimmed
  { input: "https://example.com/path/", articleId: "url_5faa4bf4918f", canonicalUrl: "https://example.com/path", sourceKind: "web" },
  // default https port (443) dropped -> identical to the trimmed-path case
  { input: "https://example.com:443/path", articleId: "url_5faa4bf4918f", canonicalUrl: "https://example.com/path", sourceKind: "web" },
  // default http port (80) dropped + trailing slash trimmed
  { input: "http://example.com:80/a/b/", articleId: "url_649028aa5462", canonicalUrl: "http://example.com/a/b", sourceKind: "web" },
  // query keys sorted into a stable order
  { input: "https://example.com/a?b=2&a=1&c=3", articleId: "url_55ed91d35e3c", canonicalUrl: "https://example.com/a?a=1&b=2&c=3", sourceKind: "web" },
  // youtu.be -> canonical watch URL, yt_ prefix
  { input: "https://youtu.be/chkfptSSepA", articleId: "yt_7ce3b01c3504", canonicalUrl: "https://www.youtube.com/watch?v=chkfptSSepA", sourceKind: "youtube" },
  // watch with extra params -> same identity as the bare video
  { input: "https://www.youtube.com/watch?v=chkfptSSepA&t=10s", articleId: "yt_7ce3b01c3504", canonicalUrl: "https://www.youtube.com/watch?v=chkfptSSepA", sourceKind: "youtube" },
  // shorts and embed resolve to the same video identity
  { input: "https://youtube.com/shorts/abc123XYZ", articleId: "yt_2fdd330a7315", canonicalUrl: "https://www.youtube.com/watch?v=abc123XYZ", sourceKind: "youtube" },
  { input: "https://www.youtube.com/embed/abc123XYZ", articleId: "yt_2fdd330a7315", canonicalUrl: "https://www.youtube.com/watch?v=abc123XYZ", sourceKind: "youtube" },
  // m.youtube host normalized
  { input: "https://m.youtube.com/watch?v=chkfptSSepA", articleId: "yt_7ce3b01c3504", canonicalUrl: "https://www.youtube.com/watch?v=chkfptSSepA", sourceKind: "youtube" },
  // Japanese path/query -> percent-encoded UTF-8 (native URL behaviour)
  { input: "https://example.com/記事?q=あ", articleId: "url_bdd392bc238b", canonicalUrl: "https://example.com/%E8%A8%98%E4%BA%8B?q=%E3%81%82", sourceKind: "web" },
  // "+" and "%20" in a query value collapse to the same canonical form
  { input: "https://example.com/a?q=a+b", articleId: "url_33a65139c3e2", canonicalUrl: "https://example.com/a?q=a+b", sourceKind: "web" },
  { input: "https://example.com/a?q=a%20b", articleId: "url_33a65139c3e2", canonicalUrl: "https://example.com/a?q=a+b", sourceKind: "web" },
  // IDN host -> punycode
  { input: "https://日本語.example/path", articleId: "url_f5d6cda56d89", canonicalUrl: "https://xn--wgv71a119e.example/path", sourceKind: "web" },
  // unparseable input -> hashed verbatim, treated as web
  { input: "not a url", articleId: "url_d8b5bf9b9fd4", canonicalUrl: "not a url", sourceKind: "web" },
  // non-http scheme is still parseable by URL and hashed as-is
  // (scheme allow-listing is an endpoint concern, not identity's)
  { input: "ftp://example.com/resource", articleId: "url_1a4e75beb389", canonicalUrl: "ftp://example.com/resource", sourceKind: "web" }
];

test("golden identity vectors are stable", () => {
  for (const vector of GOLDEN) {
    const actual = createArticleIdentity(vector.input);
    assert.deepEqual(
      { articleId: actual.articleId, canonicalUrl: actual.canonicalUrl, sourceKind: actual.sourceKind },
      { articleId: vector.articleId, canonicalUrl: vector.canonicalUrl, sourceKind: vector.sourceKind },
      `identity changed for input: ${vector.input}`
    );
  }
});

test("identity is deterministic", () => {
  for (const vector of GOLDEN) {
    const a = createArticleIdentity(vector.input);
    const b = createArticleIdentity(vector.input);
    assert.deepEqual(a, b);
  }
});

/**
 * Regression gate over real pipeline data in the sibling viewer repo.
 *
 * Records that were generated by the live pipeline must round-trip:
 * recomputing identity from their canonicalUrl must reproduce the stored
 * articleId. A few legacy hand-authored fixture rows predate the current
 * logic (e.g. a youtu.be URL stored under a "url_" key) and are exempted by
 * KNOWN_STALE; everything else must match.
 */
const KNOWN_STALE = new Set([
  "url_a8f31c9d4e21b7aa", // youtu.be fixture stored with url_ prefix + 16-char hash
  "yt_c12b8d4429", // note.com web fixture stored with yt_ prefix
  "url_b72a901e10" // example.com/report fixture, 10-char hash
]);

test("live articles.json records round-trip (excluding known stale fixtures)", () => {
  const here = path.dirname(fileURLToPath(import.meta.url));
  const articlesPath = path.resolve(here, "../../../multimodal-article-viewer/articles.json");
  if (!existsSync(articlesPath)) {
    return; // sibling repo not present in this checkout; skip
  }

  const articles = JSON.parse(readFileSync(articlesPath, "utf8")) as Array<{
    articleId: string;
    canonicalUrl?: string;
    originalUrl?: string;
  }>;

  for (const article of articles) {
    if (KNOWN_STALE.has(article.articleId)) {
      continue;
    }
    const recomputed = createArticleIdentity(article.canonicalUrl || article.originalUrl || "");
    assert.equal(
      recomputed.articleId,
      article.articleId,
      `stored articleId ${article.articleId} no longer matches recompute from ${article.canonicalUrl}`
    );
  }
});
